import { Coupan } from '../coupan/coupan.model';
import { CouponUsageDetail } from '../coupan/couponUsageDetail.model';
import { OrderAddress } from './orderAddress.model';
import { OrderPayment } from './orderPayment.model';
import { OrderProductAddon } from './orderProductAddon.model';
import { OrderProductVariation } from './orderProductVariation.model';

import { TaxPaidByType } from '../common/taxPaidByType.model';
import { User } from '../user.model';
import { ZipCode } from '../common/zipCode.model';
import { UserComment } from '../user/userComment.model';
import { UserPointTransaction } from '../user/userPointTransaction.model';
import { OrderProduct } from './orderProduct.model';
import { UserAddress } from '../userAddress.model';
import { Product } from '@app/models/product/product.model';
import { ProductAddon } from '@app/models/product/productAddon.model';
import { DropDownItem } from '../base/dropdownitem';
import { OrderAdditionalItemGroupWiseModel } from './orderadditionalitemgroupwise.model';
import { DropDownRestaurantItemDto } from '../common/restaurantfilter.model';
import { ZipcodeModel } from '../zipCodeList.model';
import { Restaurant } from '../restaurants/restaurant.model';
import { OrderProductTabDto } from './orderProductTab.model';
import { ProductVariation } from '../product/productVariation.model';

export class Order {
    Id: number;
    CreatedDate: Date;
    DeliveryDate: string;
    OrderStatusId: number;
    OrderNumber: number;
    UserId: number;
    CreatedUserId: number;
    RestaurantId: number;
    OrderChannelId: number;
    IsGroupOrder: boolean;
    EarnedPoints: number;
    RedeemedPoints: number;
    GratuityId: number;
    GratuityAmount: number;
    GratuityPercent: number;
    DeliveryFee: number;
    TotalAddonAmount: number;
    TotalVariationAmount: number;
    HouseItemSubTotalAmount: number;
    HouseItemTaxAmount: number;
    DiscountAmount: number;
    SubTotalAmount: number;
    TaxAmount: number;
    TotalAmount: number;
    TaxPercent: number;
    IsProposal: boolean;
    LastModifiedUserId: number;
    LastModifiedDate: Date;
    AdditionalFee: number;
    Note: string;
    DriverInstruction: string;
    ContactPhoneNumber: string;
    PlateNumber: number;
    IsAsapOrder: boolean;
    TaxPaidByTypeId: number;
    CouponId: number;
    Instructions: string;
    Coupon: Coupan;
    CouponUsageDetail: CouponUsageDetail[];
    OrderAddress: OrderAddress;
    OrderPayments: OrderPayment[];
    // OrderProducts: OrderProduct[];
    // OrderProductAddons: OrderProductAddon[];
    // OrderProductVariations: OrderProductVariation[];
    Restaurant: Restaurant;
    TaxPaidByType: TaxPaidByType;
    Customer: User;
    CreatedUserName: string;
    LastModifiedUserName: string;
    ZipCode: ZipCode;
    UserComments: UserComment;
    UserPointTransactions: UserPointTransaction[];
    // TODO: need to add all the vm properties.
    UserDeliveryAddressList: UserAddress[];
    UserBillingAddressList: UserAddress[];
    DrpProductList: Product[];
    DrpRestaurantList: DropDownRestaurantItemDto[];
    DrpGratuityPercentageList: DropDownItem[];
    DrpZipCodeList: ZipcodeModel[];
    SelectedUserAddresses: UserAddress[];
    IsSaveCustomerDeliveryAddress: boolean;
    IsSaveCustomerBillingAddress: boolean;
    RestaurantName: string;
    CoupanName: string;
    IsReOrder: boolean;
    OrderAdditionalItemList: OrderAdditionalItemGroupWiseModel[];
    ProductCategoryList: OrderProductTabDto[];
    ProductAddonList: ProductAddon[];
    ProductVariationList: ProductVariation[];
}